AppBundle\Entity\BoothVerificationUser:
  type: entity
  table: booth_verification_user
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    uid:
      type: integer
      nullable: false
      length: 11
      options:
        fixed: false
        comment: 会员管理UID
    createAt:
      type: datetime
        nullable: false
        options:
          comment: 创建时间
        column: create_at
  lifecycleCallbacks: {  }