AppBundle\Entity\Member:
    type: entity
    table: member
    repositoryClass: AppBundle\Repository\MemberRepository
    id:
        uid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        openid:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 微信openid
        formid:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 推送码
        mobile:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 手机号码
        level:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 会员等级
        parentid:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 父ID
        credit:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 余额
        lastloginip:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 上一次登录IP
        lastlogintime:
            type: datetime
            nullable: false
            options:
                comment: 上一次登录时间
        profileid:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 详情资料关联ID
        regtime:
            type: datetime
            nullable: false
            options:
                comment: 注册时间
        enable:
            type: boolean
            nullable: false
            options:
                comment: 是否可用
    lifecycleCallbacks: {  }
