AppBundle\Entity\MemberProfile:
    type: entity
    table: member_profile
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        avatar:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 头像
        birthday:
            type: datetime
            nullable: false
            options:
                comment: 生日
        gender:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 性别
        nickname:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 昵称
    lifecycleCallbacks: {  }
