AppBundle\Entity\SalesRecord:
    type: entity
    table: sales_record
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uid:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 会员UID
        boothId:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 摊位UID
            column: booth_id
        goodsName:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 商品名称
            column: goods_name
        goodsCount:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 售出数量
            column: goods_count
        goodsTotal:
            type: float
            nullable: false
            precision: 9
            scale: 2
            options:
                comment: 售出总价
            column: goods_total
        reportTime:
            type: datetime
            nullable: false
            options:
                comment: 上报时间
            column: report_time
    lifecycleCallbacks: {  }
