AppBundle\Entity\Admin:
    type: entity
    table: admin
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 用户
        psw:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 密码
        roleId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: role_id
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: "状态 1.可用 2.不可用\t"
        createTime:
            type: datetime
            nullable: false
            options:
                comment: 创建时间
            column: create_time
    lifecycleCallbacks: {  }
