AppBundle\Entity\BoothCategory:
    type: entity
    table: booth_category
    repositoryClass: AppBundle\Repository\BoothCategoryRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pid:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 父类ID
        title:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 分类名称
        sort:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 排序
    lifecycleCallbacks: {  }
