AppBundle\Entity\Booth:
    type: entity
    table: booth
    repositoryClass: AppBundle\Repository\BoothRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tradefair_id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 展会ID
        row:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 行
        col:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 列
        category:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 展位类型
        sort:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 排序
        title:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 展位名称
        number:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 展位编号
        size:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 面积/m²
        price:
            type: float
            nullable: false
            precision: 9
            scale: 2
            options:
                comment: 价格
        picture:
            type: string
            nullable: false
            length: 1000
            options:
                fixed: false
                comment: 展位图片集
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: 详情
        visits:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 访问次数
        enable:
            type: boolean
            nullable: false
            options:
                comment: 是否可用
    lifecycleCallbacks: {  }
