AppBundle\Entity\Settings:
    type: entity
    table: settings
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        configKey:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
                comment: 配置项KEY
            column: config_key
        configValue:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: 配置项值
            column: config_value
    lifecycleCallbacks: {  }
